name: 'Update GitBoard.io Dashboard'
description: 'Sends job status information to GitBoard.io. GitBoard.io makes GitHub Actions visible, providing a build status dashboard.'
branding:
  icon: grid
  color: green
inputs:
  username:
    description: 'GitBoard.io username, dictates which GitBoard.io account will reflect the job status. A users GitBoard.io username can be found at https://gitboard.io/profile. Multiple account usernames can be supplied. Separate account usernames with a comma. Align corresponding account usernames and account keys.'
    required: true
  key:
    description: 'GitBoard.io users api key, authenticates the request to the GitBoard.io api. This should be kept secret, we recommend storing this in a GitHub secret. A users GitBoard.io api key can be found at https://gitboard.io/profile. Multiple account keys can be supplied. Separate account keys with a comma. Align corresponding account usernames and account keys.'
    required: true
  dashboard:
      description: 'GitBoard.io dashboard reference, dictates which GitBoard.io dashboard will reflect the job status. Defaults to a users default dashboard. A users GitBoard.io dashboard references can be found at https://gitboard.io/settings. Multiple dashboard references can be supplied. Separate dashboard references with a comma'
      required: true
  status:
    description: 'job status'
    default: ${{ job.status }}
runs:
  using: 'node16'
  pre: 'pre/index.js'
  main: 'main/index.js'
  post: 'post/index.js'
