name: 'Update GitBoard.io Dashboard'
description: 'Sends job status information to GitBoard.io. GitBoard.io makes GitHub Actions visible, providing a build status dashboard.'
branding:
  icon: grid
  color: green
inputs:
  username:
    description: 'GitBoard.io account username. Multiple account usernames can be supplied. Separate account usernames with a comma. Align corresponding account usernames and account keys.'
    required: true
  key:
    description: 'GitBoard.io account key, Multiple account keys can be supplied. Separate account keys with a comma. Align corresponding account usernames and account keys.'
    required: true
  status:
    description: 'job status'
    default: ${{ job.status }}
runs:
  using: 'node16'
  pre: 'pre/index.js'
  main: 'main/index.js'
  post: 'post/index.js'
